// src/constants/spotlightData.ts
import type { BlogPost } from "@/types/spotlight";
import { PLAYER_IMAGES } from "./spotlightImages";

// Sample initial data - will be replaced by API later
export const SAMPLE_BLOG_POSTS: BlogPost[] = [
  {
    id: "1",
    title: "The Rise of Youth Football Academies in Europe",
    excerpt: "How grassroots programs are shaping the next generation of football superstars...",
    content: "<p>Full content here...</p>",
    sport: "football",
    author: {
      id: "admin1",
      name: "James Rodriguez",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    heroImage: PLAYER_IMAGES.football.hero,
    playerImage: PLAYER_IMAGES.football.player,
    createdAt: "2024-05-15T10:00:00Z",
    updatedAt: "2024-05-15T10:00:00Z",
    readTime: 5,
    tags: ["football", "academy", "youth"],
    featured: true,
    viewCount: 1240,
    comments: [],
  },
  {
    id: "2",
    title: "Basketball Analytics: The Numbers Behind the Game",
    excerpt: "How data science is revolutionizing player recruitment and game strategy...",
    content: "<p>Full content here...</p>",
    sport: "basketball",
    author: {
      id: "admin1",
      name: "James Rodriguez",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    heroImage: PLAYER_IMAGES.basketball.hero,
    playerImage: PLAYER_IMAGES.basketball.player,
    createdAt: "2024-05-10T14:30:00Z",
    updatedAt: "2024-05-10T14:30:00Z",
    readTime: 7,
    tags: ["basketball", "analytics", "data"],
    featured: true,
    viewCount: 892,
    comments: [],
  },
  {
    id: "3",
    title: "Tennis Comeback Stories That Inspire",
    excerpt: "Athletes who defied odds and returned to the court stronger than ever...",
    content: "<p>Full content here...</p>",
    sport: "tennis",
    author: {
      id: "admin2",
      name: "Sarah Williams",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    heroImage: PLAYER_IMAGES.tennis.hero,
    playerImage: PLAYER_IMAGES.tennis.player,
    createdAt: "2024-05-05T09:15:00Z",
    updatedAt: "2024-05-05T09:15:00Z",
    readTime: 6,
    tags: ["tennis", "comeback", "inspiration"],
    featured: false,
    viewCount: 567,
    comments: [],
  },
  {
    id: "4",
    title: "Volleyball: The Ultimate Team Sport",
    excerpt: "Why communication and trust matter more than individual skill...",
    content: "<p>Full content here...</p>",
    sport: "volleyball",
    author: {
      id: "admin1",
      name: "James Rodriguez",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    heroImage: PLAYER_IMAGES.volleyball.hero,
    playerImage: PLAYER_IMAGES.volleyball.player,
    createdAt: "2024-04-28T16:20:00Z",
    updatedAt: "2024-04-28T16:20:00Z",
    readTime: 4,
    tags: ["volleyball", "teamwork", "leadership"],
    featured: false,
    viewCount: 345,
    comments: [],
  },
  {
    id: "5",
    title: "Cricket World Cup 2024: Early Predictions",
    excerpt: "Which teams are looking strongest ahead of this year's championship?",
    content: "<p>Full content here...</p>",
    sport: "cricket",
    author: {
      id: "admin2",
      name: "Sarah Williams",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    heroImage: PLAYER_IMAGES.cricket.hero,
    playerImage: PLAYER_IMAGES.cricket.player,
    createdAt: "2024-04-20T11:00:00Z",
    updatedAt: "2024-04-20T11:00:00Z",
    readTime: 8,
    tags: ["cricket", "worldcup", "predictions"],
    featured: false,
    viewCount: 2100,
    comments: [],
  },
  {
    id: "6",
    title: "Badminton: Speed, Agility, Precision",
    excerpt: "Breaking down the physics behind the fastest racket sport...",
    content: "<p>Full content here...</p>",
    sport: "badminton",
    author: {
      id: "admin1",
      name: "James Rodriguez",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    heroImage: PLAYER_IMAGES.badminton.hero,
    playerImage: PLAYER_IMAGES.badminton.player,
    createdAt: "2024-04-15T13:45:00Z",
    updatedAt: "2024-04-15T13:45:00Z",
    readTime: 5,
    tags: ["badminton", "speed", "training"],
    featured: false,
    viewCount: 423,
    comments: [],
  },
];