// Frontend-only dummy tournaments used as a fallback when the backend
// returns no data. They mirror the Tournament shape so cards render normally.
import type { Tournament } from "@/types";
import { getSportImage } from "./sportImages";

const daysFromNow = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString();
};

export const DUMMY_TOURNAMENTS: Tournament[] = [
  {
    id: "demo-1",
    name: "Spring Football Championship",
    sport: "football",
    description: "The biggest inter-college football tournament of the spring season featuring 16 elite squads.",
    bannerUrl: getSportImage("football", "banner"),
    teamSlots: 16,
    teamCount: 12,
    startDate: daysFromNow(7),
    registrationDeadline: daysFromNow(3),
    estimatedMatchDuration: 90,
    visibility: "public",
    status: "registration",
    inviteCode: "demo-football-spring",
    createdAt: daysFromNow(-14),
    adminName: "Coach Daniels",
  },
  {
    id: "demo-2",
    name: "Campus Basketball Showdown",
    sport: "basketball",
    description: "Fast-paced 5v5 hardcourt action — eight teams battling for the campus crown.",
    bannerUrl: getSportImage("basketball", "banner"),
    teamSlots: 8,
    teamCount: 8,
    startDate: daysFromNow(-2),
    registrationDeadline: daysFromNow(-5),
    estimatedMatchDuration: 60,
    visibility: "public",
    status: "active",
    inviteCode: "demo-basketball-showdown",
    createdAt: daysFromNow(-21),
    adminName: "Athletics Dept.",
  },
  {
    id: "demo-3",
    name: "University Tennis Open",
    sport: "tennis",
    description: "Singles knockout bracket open to all enrolled students. Best-of-three sets format.",
    bannerUrl: getSportImage("tennis", "banner"),
    teamSlots: 16,
    teamCount: 9,
    startDate: daysFromNow(14),
    registrationDeadline: daysFromNow(10),
    estimatedMatchDuration: 75,
    visibility: "public",
    status: "registration",
    inviteCode: "demo-tennis-open",
    createdAt: daysFromNow(-10),
    adminName: "Tennis Club",
  },
  {
    id: "demo-4",
    name: "Volleyball Beach Classic",
    sport: "volleyball",
    description: "6v6 indoor volleyball tournament — all divisions welcome. Sets-based scoring.",
    bannerUrl: getSportImage("volleyball", "banner"),
    teamSlots: 8,
    teamCount: 6,
    startDate: daysFromNow(21),
    registrationDeadline: daysFromNow(14),
    estimatedMatchDuration: 60,
    visibility: "public",
    status: "upcoming",
    inviteCode: "demo-volleyball-classic",
    createdAt: daysFromNow(-7),
    adminName: "Recreation Office",
  },
  {
    id: "demo-5",
    name: "Inter-Hall Cricket League",
    sport: "cricket",
    description: "T20-format cricket league between residence halls. Crown your hall champion.",
    bannerUrl: getSportImage("cricket", "banner"),
    teamSlots: 8,
    teamCount: 8,
    startDate: daysFromNow(-30),
    registrationDeadline: daysFromNow(-35),
    estimatedMatchDuration: 180,
    visibility: "public",
    status: "completed",
    inviteCode: "demo-cricket-league",
    createdAt: daysFromNow(-60),
    adminName: "Hall Council",
  },
  {
    id: "demo-6",
    name: "Badminton Doubles Cup",
    sport: "badminton",
    description: "Mixed doubles knockout — fast rallies, big upsets. Sign up with a partner.",
    bannerUrl: getSportImage("badminton", "banner"),
    teamSlots: 16,
    teamCount: 11,
    startDate: daysFromNow(10),
    registrationDeadline: daysFromNow(5),
    estimatedMatchDuration: 45,
    visibility: "public",
    status: "registration",
    inviteCode: "demo-badminton-cup",
    createdAt: daysFromNow(-12),
    adminName: "Badminton Society",
  },
];
